In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [3]:
type(x)

numpy.ndarray

In [5]:
x[1,2]
#second row third column

6

In [6]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
x[1:2,:2]

array([[4, 5]])

In [8]:
x1 = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])

In [9]:
x1

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

In [10]:
np.nonzero(x1)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

# axis

In [11]:
# https://docs.scipy.org/doc/numpy-1.10.0/glossary.html
# A 2-dimensional array has two corresponding axes: 
# the first running vertically downwards across rows (axis 0),
# and the second running horizontally across columns (axis 1).

In [12]:
x3 = np.arange(12).reshape((3,4))
x3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
x3.sum(axis=1)
# sum horizontally

array([ 6, 22, 38])

In [16]:
x3.sum(axis=0)
# sum vertically

array([12, 15, 18, 21])

In [18]:
x3.sum()
# sum all

66

# sort

In [22]:
x4 = np.array([[1,4],[3,1],[6,5]])
x4

array([[1, 4],
       [3, 1],
       [6, 5]])

In [25]:
np.sort(x4)
# sort horizontally

array([[1, 4],
       [1, 3],
       [5, 6]])

In [26]:
np.sort(x4, axis=1)
# sort horizontally

array([[1, 4],
       [1, 3],
       [5, 6]])

In [27]:
np.sort(x4, axis=0)
# sort vertically

array([[1, 1],
       [3, 4],
       [6, 5]])

In [29]:
np.sort(x4, axis=None)
# sort flattened

array([1, 1, 3, 4, 5, 6])

# where

In [30]:
x5 = np.arange(10)
x5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.where(x5<5, x5, x5 * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [32]:
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

# isnan

In [38]:
x6 = np.array([np.nan, 1, -2])
np.isnan(x6)

array([ True, False, False])

# logical_and

In [39]:
np.logical_and(True, False)

False

In [40]:
np.logical_and(True, True)

True

In [41]:
np.logical_and(True, np.logical_and(False, True))

False

In [42]:
np.logical_and([True,False], [False,True])

array([False, False])

In [43]:
np.logical_and([True,False], [True,False])

array([ True, False])

In [44]:
x7 = np.arange(10)
x7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.logical_and(x7>2,x7<8)

array([False, False, False,  True,  True,  True,  True,  True, False,
       False])

In [47]:
np.array([True, False]) & np.array([True, True]) 
# The & operator can be used as a shorthand for np.logical_and on boolean ndarrays.

array([ True, False])

In [49]:
np.logical_and(np.array([True, False]), np.array([True, True]))

array([ True, False])

In [50]:
[True, False] & [True, True]

TypeError: unsupported operand type(s) for &: 'list' and 'list'