In [1]:
# ! pip install yfinance

In [2]:
import yfinance as yf
import pandas as pd
import numpy as np
import warnings

In [3]:
df=yf.download("^HSI","2018-01-01")

[*********************100%***********************]  1 of 1 completed


In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df["Open"]

Date
2018-01-02    30028.289062
2018-01-03    30658.730469
2018-01-04    30691.710938
2018-01-05    30893.859375
2018-01-08    30895.089844
                  ...     
2023-06-09    19333.429688
2023-06-12    19440.990234
2023-06-13    19355.650391
2023-06-14    19547.580078
2023-06-15    19626.800781
Name: Open, Length: 1343, dtype: float64

In [6]:
type(df["Open"])

pandas.core.series.Series

### Series constructor from numpy array

In [7]:
data = np.array(['python','php','java'])

In [8]:
type(data)

numpy.ndarray

In [9]:
series = pd.Series(data)

In [10]:
series

0    python
1       php
2      java
dtype: object

In [11]:
type(series)

pandas.core.series.Series

### Series constructor from Dict

In [12]:
data = {'Courses' :"pandas", 'Fees' : 20000, 'Duration' : "30days"}
s2 = pd.Series(data)

In [13]:
type(s2)

pandas.core.series.Series

### Series constructor from List

In [14]:
data = ['python','php','java']
s3 = pd.Series(data, index=['r1', 'r2','r3'])
type(s3)

pandas.core.series.Series

In [15]:
s3

r1    python
r2       php
r3      java
dtype: object

In [16]:
df.index

DatetimeIndex(['2018-01-02', '2018-01-03', '2018-01-04', '2018-01-05',
               '2018-01-08', '2018-01-09', '2018-01-10', '2018-01-11',
               '2018-01-12', '2018-01-15',
               ...
               '2023-06-02', '2023-06-05', '2023-06-06', '2023-06-07',
               '2023-06-08', '2023-06-09', '2023-06-12', '2023-06-13',
               '2023-06-14', '2023-06-15'],
              dtype='datetime64[ns]', name='Date', length=1343, freq=None)

In [17]:
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [18]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [19]:
technologies = [ ["Spark",20000, "30days"], 
                 ["pandas",20000, "40days"], 
               ]
df=pd.DataFrame(technologies)

column_names=["Courses","Fee","Duration"]
row_label=["a","b"]
df=pd.DataFrame(technologies,columns=column_names,index=row_label)
df

Courses    Fee Duration
a   Spark  20000   30days
b  pandas  20000   40days

In [20]:
df.dtypes

Courses     object
Fee          int64
Duration    object
dtype: object

In [21]:
types={'Courses': str,'Fee':float,'Duration':str}
df=df.astype(types)

In [22]:
df.dtypes

Courses      object
Fee         float64
Duration     object
dtype: object

In [23]:
# Create DataFrame from Dictionary
technologies_dict = {
    'Courses':["Spark","PySpark","Hadoop"],
    'Fee' :[20000,25000,26000],
    'Duration':['30day','40days','35days'],
    'Discount':[1000,2300,1500]
              }
df = pd.DataFrame(technologies_dict)

In [24]:
df

Courses    Fee Duration  Discount
0    Spark  20000    30day      1000
1  PySpark  25000   40days      2300
2   Hadoop  26000   35days      1500

In [25]:
technologies_dict2   = ({
    'Courses':["Spark","PySpark","Hadoop","Python","Pandas",None,"Spark","Python"],
    'Fee' :[22000,25000,23000,24000,np.nan,25000,25000,22000],
    'Duration':['30day','50days','55days','40days','60days','35day','','50days'],
    'Discount':[1000,2300,1000,1200,2500,1300,1400,1600]
          })
row_labels=['r0','r1','r2','r3','r4','r5','r6','r7']
df = pd.DataFrame(technologies_dict2, index=row_labels)

In [26]:
type(technologies_dict2)

dict

In [27]:
type(row_labels)

list

In [28]:
df


Courses      Fee Duration  Discount
r0    Spark  22000.0    30day      1000
r1  PySpark  25000.0   50days      2300
r2   Hadoop  23000.0   55days      1000
r3   Python  24000.0   40days      1200
r4   Pandas      NaN   60days      2500
r5     None  25000.0    35day      1300
r6    Spark  25000.0               1400
r7   Python  22000.0   50days      1600

In [29]:
df.shape

(8, 4)

In [30]:
df.size

32

In [31]:
df.empty

False

In [32]:
df.columns

Index(['Courses', 'Fee', 'Duration', 'Discount'], dtype='object')

In [33]:
df.columns.values

array(['Courses', 'Fee', 'Duration', 'Discount'], dtype=object)

In [34]:
df.index


Index(['r0', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7'], dtype='object')

In [35]:
df.index.values

array(['r0', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7'], dtype=object)

In [36]:
df.dtypes

Courses      object
Fee         float64
Duration     object
Discount      int64
dtype: object

In [37]:
type(['Courses', 'Fee', 'Duration', 'Discount'])

list

In [38]:
df['Fee']

r0    22000.0
r1    25000.0
r2    23000.0
r3    24000.0
r4        NaN
r5    25000.0
r6    25000.0
r7    22000.0
Name: Fee, dtype: float64

In [39]:
type(df['Fee']) # When collect one column, it is a series

pandas.core.series.Series

In [40]:
df[['Fee','Duration']]

Fee Duration
r0  22000.0    30day
r1  25000.0   50days
r2  23000.0   55days
r3  24000.0   40days
r4      NaN   60days
r5  25000.0    35day
r6  25000.0         
r7  22000.0   50days

In [41]:
type(df[['Fee','Duration']]) # When collect one column, it is a dataframe

pandas.core.frame.DataFrame

In [42]:
df[df['Fee'] == 22000] # where fee = 2000

Courses      Fee Duration  Discount
r0   Spark  22000.0    30day      1000
r7  Python  22000.0   50days      1600

In [43]:
df[(df['Fee'] == 22000) & (df['Discount'] > 1500)] # where fee = 2000 and discount > 1500

Courses      Fee Duration  Discount
r7  Python  22000.0   50days      1600

In [44]:
df.iloc[list((df['Fee'] == 22000) & (df['Discount'] > 1500)) ] # where fee = 2000 and discount > 1500

Courses      Fee Duration  Discount
r7  Python  22000.0   50days      1600

In [45]:
df[(df['Fee'] == 22000) | (df['Discount'] > 1500)] # where fee = 2000 or discount > 1500

Courses      Fee Duration  Discount
r0    Spark  22000.0    30day      1000
r1  PySpark  25000.0   50days      2300
r4   Pandas      NaN   60days      2500
r7   Python  22000.0   50days      1600

In [46]:
df[(df['Fee'] == 22000) | (df['Discount'] > 1500)].iloc[2:]

Courses      Fee Duration  Discount
r4  Pandas      NaN   60days      2500
r7  Python  22000.0   50days      1600

In [47]:
df[(df['Fee'] == 22000) | (df['Discount'] > 1500)].iloc[:1,1:]  # iloc[row range, column range]

Fee Duration  Discount
r0  22000.0    30day      1000

In [48]:
technologies_dict2   = ({
    'Courses':["Spark","PySpark","Hadoop","Python","Pandas","Hadoop","Spark","Python","NA"],
    'Fee' :[22000,25000,23000,24000,26000,25000,25000,22000,1500],
    'Duration':['30days','50days','55days','40days','60days','35days','30days','50days','40days'],
    'Discount':[1000,2300,1000,1200,2500,None,1400,1600,0]
          })
df2 = pd.DataFrame(technologies_dict2)

In [49]:
df2

Courses    Fee Duration  Discount
0    Spark  22000   30days    1000.0
1  PySpark  25000   50days    2300.0
2   Hadoop  23000   55days    1000.0
3   Python  24000   40days    1200.0
4   Pandas  26000   60days    2500.0
5   Hadoop  25000   35days       NaN
6    Spark  25000   30days    1400.0
7   Python  22000   50days    1600.0
8       NA   1500   40days       0.0

In [50]:
df2.groupby(["Courses"]).sum() ## select courses, sum(fee) from df2 group by courses

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\976841659.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2.groupby(["Courses"]).sum() ## select courses, sum(fee) from df2 group by courses


Fee  Discount
Courses                 
Hadoop   48000    1000.0
NA        1500       0.0
Pandas   26000    2500.0
PySpark  25000    2300.0
Python   46000    2800.0
Spark    47000    2400.0

In [51]:
type(df2.groupby(["Courses"]).sum())

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\1321169555.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  type(df2.groupby(["Courses"]).sum())


pandas.core.frame.DataFrame

In [52]:
df2.groupby(['Courses','Duration']).sum().reset_index()

Courses Duration    Fee  Discount
0   Hadoop   35days  25000       0.0
1   Hadoop   55days  23000    1000.0
2       NA   40days   1500       0.0
3   Pandas   60days  26000    2500.0
4  PySpark   50days  25000    2300.0
5   Python   40days  24000    1200.0
6   Python   50days  22000    1600.0
7    Spark   30days  47000    2400.0

In [53]:
df2.groupby(by=['Courses'], dropna=False).sum()

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\2830196835.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2.groupby(by=['Courses'], dropna=False).sum()


Fee  Discount
Courses                 
Hadoop   48000    1000.0
NA        1500       0.0
Pandas   26000    2500.0
PySpark  25000    2300.0
Python   46000    2800.0
Spark    47000    2400.0

In [54]:
df2.groupby(by=['Courses'], dropna=True).sum()  ## select courses, sum(fee) from df2 
## where courses is not null group by courses

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\271784089.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2.groupby(by=['Courses'], dropna=True).sum()  ## select courses, sum(fee) from df2


Fee  Discount
Courses                 
Hadoop   48000    1000.0
NA        1500       0.0
Pandas   26000    2500.0
PySpark  25000    2300.0
Python   46000    2800.0
Spark    47000    2400.0

In [55]:
df2.groupby(by=['Courses'], sort=False).sum()

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\1055539439.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2.groupby(by=['Courses'], sort=False).sum()


Fee  Discount
Courses                 
Spark    47000    2400.0
PySpark  25000    2300.0
Hadoop   48000    1000.0
Python   46000    2800.0
Pandas   26000    2500.0
NA        1500       0.0

In [56]:
letters='abcdefghijklmnopqrstuvwxyz'

In [57]:
len(letters)


26

In [58]:
letters[0]

'a'

In [59]:
letters[0:3]

'abc'

In [60]:
letters[1:3]

'bc'

In [61]:
letters[1:2]

'b'

In [62]:
letters[1:-1]

'bcdefghijklmnopqrstuvwxy'

In [63]:
letters[1:]

'bcdefghijklmnopqrstuvwxyz'

In [64]:
letters[0]

'a'

In [65]:
letters[2]

'c'

In [66]:
'b' + letters[1:]

'bbcdefghijklmnopqrstuvwxyz'

In [67]:
letters.replace('a','b')

'bbcdefghijklmnopqrstuvwxyz'

In [68]:
letters

'abcdefghijklmnopqrstuvwxyz'

In [69]:
letters.strip("a")

'bcdefghijklmnopqrstuvwxyz'

In [70]:
letters


'abcdefghijklmnopqrstuvwxyz'

In [71]:
letters.strip("z").strip("a").strip("b").strip("k")

'cdefghijklmnopqrstuvwxy'

In [72]:
letters.strip("a").strip("b")

'cdefghijklmnopqrstuvwxyz'

In [73]:
letters=letters.strip("a").strip("b")

In [74]:
letters

'cdefghijklmnopqrstuvwxyz'

In [75]:
data="1;2;4;6;8"

In [76]:
data.split(";")

['1', '2', '4', '6', '8']

In [77]:
type(data.split(";"))

list

In [78]:
",".join(data.split(";"))

'1,2,4,6,8'

In [79]:
type(",".join(data.split(";")))

str

In [80]:
[1,2,3,4,5,6][0:3]

[1, 2, 3]

In [81]:
[1,2,3,4,5,6][1:3]

[2, 3]

In [82]:
[1,2,3,4,5,6][0]

1

In [83]:
type([1,2,3,4,5,6][0])

int

In [84]:
type([1,2,3,4,5,6][0:3])

list

In [85]:
[[1,2,3],[4,5,6],[7,8,9]][1]

[4, 5, 6]

In [86]:
[[1,2,3],[4,5,6],[7,8,9]][1][0:2]

[4, 5]

In [87]:
type((1,2,3))

tuple

In [88]:
dict8={"Peter": [1,2,3], "Mary": [4,5,6]}   # same like json with key, value pairing

In [89]:
dict8["Peter"]

[1, 2, 3]

In [90]:
dict8["Peter"][2]

3

In [91]:
set8={"Peter","Alice"}

In [92]:
type(set8)

set

In [93]:
set8

{'Alice', 'Peter'}

In [94]:
type(dict8)

dict

In [95]:
type(df)

pandas.core.frame.DataFrame

In [96]:
type("abc")

str

In [97]:
listAppend=[1,2,3,4,5,6]

In [98]:
listAppend.append(7)

In [99]:
listAppend

[1, 2, 3, 4, 5, 6, 7]

In [100]:
listExtend=(8,9,10)

In [101]:
listAppend.extend(listExtend)

In [102]:
listAppend

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [103]:
vowel = ['a', 'e', 'i', 'u']


In [104]:
vowel.insert(3, 'o')

In [105]:
vowel

['a', 'e', 'i', 'o', 'u']

In [106]:
prime_numbers = [2, 3, 5, 7, 9, 11]

In [107]:
prime_numbers.remove(9)

In [108]:
prime_numbers

[2, 3, 5, 7, 11]

In [109]:
prime_numbers.pop(2)

5

In [110]:
prime_numbers

[2, 3, 7, 11]

In [111]:
prime_numbers.sort(reverse=True)

In [112]:
prime_numbers

[11, 7, 3, 2]

In [113]:
prime_numbers.sort()

In [114]:
prime_numbers

[2, 3, 7, 11]

In [115]:
len(prime_numbers)

4

In [116]:
prime_numbers.count(7)

1

In [117]:
prime_numbers.count(17)

0

In [118]:
for i in prime_numbers:
    if(i == 4):
        print("Element Exists")

In [119]:
for i in prime_numbers:
    if(i == 11):
        print("Element Exists")

Element Exists


In [120]:
7 in prime_numbers

True

In [121]:
4 in prime_numbers

False

In [122]:
days=[1,2,3,13,5,6,13,14]

In [123]:
n=days.count(13)

In [124]:
n

2

In [125]:
days=["1","2","3","13","5","6","13","14"]
n = days.count("13")
i = 0
while i < n:
    days.remove("13")
    i += 1
print(days)

['1', '2', '3', '5', '6', '14']


In [126]:
days=["1","2","3","13","5","6","13","14"]
days2 = []
for day in days:
    if day != "13":
        days2.append(day)
print(days2)

['1', '2', '3', '5', '6', '14']


## 2023-06-8 Thursday

In [127]:
daySchDict = {
"Monday":"Shopping",
"Tuesday":"Reading",
"Wednesday":"Sleeping",
"Thursday":"Working",
"Friday":"Reading"
}

In [128]:
type(daySchDict)

dict

In [129]:
daySchDict["Tuesday"]

'Reading'

In [130]:
daySchDict = {
"Monday":"Shopping",
"Tuesday":"Reading",
"Wednesday":"Sleeping",
"Thursday":"Working",
"Friday":"Reading"
}
daySchDict["Saturday"]="Playing"  ## append new key-value pairs
daySchDict["Sunday"]="Resting"
print(daySchDict)



{'Monday': 'Shopping', 'Tuesday': 'Reading', 'Wednesday': 'Sleeping', 'Thursday': 'Working', 'Friday': 'Reading', 'Saturday': 'Playing', 'Sunday': 'Resting'}


In [131]:
daySchDict = {
"Monday":"Shopping",
"Tuesday":"Reading",
"Wednesday":"Sleeping",
"Thursday":"Working",
"Friday":"Reading"
}
daySchDict["Thursday"]="Hiking"  ## update key-value pairs
daySchDict["Tuesday"]="Walking"
print(daySchDict)


{'Monday': 'Shopping', 'Tuesday': 'Walking', 'Wednesday': 'Sleeping', 'Thursday': 'Hiking', 'Friday': 'Reading'}


In [132]:
daySchDict = {
"Monday":"Shopping",
"Tuesday":"Reading",
"Wednesday":"Sleeping",
"Thursday":"Working",
"Friday":"Reading"
}
# append by a new dict
daySchNew = {
"Saturday":"Playing",
"Sunday":"Resting"
}

daySchDict.update(daySchNew)
print(daySchDict)

{'Monday': 'Shopping', 'Tuesday': 'Reading', 'Wednesday': 'Sleeping', 'Thursday': 'Working', 'Friday': 'Reading', 'Saturday': 'Playing', 'Sunday': 'Resting'}


In [133]:
daySchDict = {
"Monday":"Shopping",
"Tuesday":"Reading",
"Wednesday":"Sleeping",
"Thursday":"Working",
"Friday":"Reading"
}
# update by a new dict
daySchNew = {
"Friday":"Playing",
"Sunday":"Resting"
}

daySchDict.update(daySchNew)
print(daySchDict)

{'Monday': 'Shopping', 'Tuesday': 'Reading', 'Wednesday': 'Sleeping', 'Thursday': 'Working', 'Friday': 'Playing', 'Sunday': 'Resting'}


In [134]:
daySchDict = {
"Monday":"Shopping",
"Tuesday":"Reading",
"Wednesday":"Sleeping",
"Thursday":"Working",
"Friday":"Reading"
}
del daySchDict["Wednesday"]   ## del a key
print(daySchDict)

{'Monday': 'Shopping', 'Tuesday': 'Reading', 'Thursday': 'Working', 'Friday': 'Reading'}


In [135]:
def print_greeting(name):     ## define a funciton
    sentence = "Good Morning" + " " + name
    print(sentence)
print_greeting("Thomson Yeung")
    

Good Morning Thomson Yeung


### Ndarray from numpy

In [136]:
nums = np.array([3.14,4.00,2.00,3.00])
nums[0]

3.14

In [137]:
nums[1]

4.0

In [138]:
nums[1:3]

array([4., 2.])

In [139]:
nums[1:3][0]

4.0

In [140]:
nums2 = np.array([[1,2,3],[4,5,6]])

In [141]:
nums2[0]

array([1, 2, 3])

In [142]:
nums2[1][1:3]

array([5, 6])

In [143]:
type(nums2)

numpy.ndarray

In [144]:
nums2.ndim

2

In [145]:
nums2.shape

(2, 3)

In [146]:
nums2.size

6

In [147]:
range(2,5)

range(2, 5)

In [148]:
type(range(2,5))

range

### The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and stops before a specified number.

In [149]:
x = range(6)
for n in x:
  print(n)

0
1
2
3
4
5


In [150]:
x = range(1,6)
for n in x:
  print(n)

1
2
3
4
5


In [151]:
x = range(3,6)
for n in x:
  print(n)

3
4
5


In [152]:
for n in range(3,6):
  print(n)

3
4
5


In [153]:
x2=np.array([list(range(i,i+3)) for i in [2,4,6]])

In [154]:
type[x2]

type[array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])]

In [155]:
x2[1]

array([4, 5, 6])

In [156]:
x2[:2]

array([[2, 3, 4],
       [4, 5, 6]])

In [157]:
x2[:2,2]

array([4, 6])

In [158]:
x2=np.array([list(range(i,i+3)) for i in [2,4,6]])
x2[0,0]=10
x2

array([[10,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8]])

In [159]:
x3=x2[:2,:2]
x3

array([[10,  3],
       [ 4,  5]])

In [160]:
x3[0,0]=20
x3

array([[20,  3],
       [ 4,  5]])

In [161]:
x2=np.array([list(range(i,i+3)) for i in [2,4,6]])
x4=x2[:2,:2]
x4[0,0]=100
x4

array([[100,   3],
       [  4,   5]])

In [162]:
x2  ## changed

array([[100,   3,   4],
       [  4,   5,   6],
       [  6,   7,   8]])

In [163]:
x2=np.array([list(range(i,i+3)) for i in [2,4,6]])
x4=x2[:2,:2].copy()
x4[0,0]=100
x4

array([[100,   3],
       [  4,   5]])

In [164]:
x2  ## no change

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [165]:
np.array([list(range(i,i+3)) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [166]:
[
    list(range(i,i+3))
    for i in [2,4,6]
]

[[2, 3, 4], [4, 5, 6], [6, 7, 8]]

In [167]:
np.array(
[
    list(range(i,i+3))
    for i in [2,4,6]
])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [168]:
grid=np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
grid=np.arange(1,13).reshape((3,4))
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [170]:
grid=np.arange(1,13).reshape((4,3))
grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [171]:
grid1=np.arange(1,10).reshape((3,3))
grid2=np.arange(10,19).reshape((3,3))


In [172]:
grid1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
grid2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [174]:
gridSum=np.concatenate([grid1,grid2])
gridSum

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [175]:
np.vstack([grid1,grid2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [176]:
np.hstack([grid1,grid2])

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [177]:
grid1 + grid2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [178]:
grid2 - grid1

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [179]:
grid2 > grid1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [180]:
grid1 > grid2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [181]:
grid1 != grid2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [182]:
grid1 == grid2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [183]:
x1=np.array([0,1,2])
x1+5
x1

array([0, 1, 2])

In [184]:
x1=np.arange(3).reshape((3,1))

In [185]:
x1

array([[0],
       [1],
       [2]])

In [186]:
x1+5

array([[5],
       [6],
       [7]])

In [187]:
x1

array([[0],
       [1],
       [2]])

In [188]:
macros = np.array([
  [0.8, 2.9, 3.9],
  [52.4, 23.6, 36.5],
  [55.2, 31.7, 23.9],
  [14.4, 11, 4.9]
   ])
multiplier=np.array([3,3,8])
macros * multiplier

array([[  2.4,   8.7,  31.2],
       [157.2,  70.8, 292. ],
       [165.6,  95.1, 191.2],
       [ 43.2,  33. ,  39.2]])

In [189]:
macros = np.array([
  [0.8, 2.9, 3.9],
  [52.4, 23.6, 36.5],
  [55.2, 31.7, 23.9],
  [14.4, 11, 4.9]
   ])
macros * 3

array([[  2.4,   8.7,  11.7],
       [157.2,  70.8, 109.5],
       [165.6,  95.1,  71.7],
       [ 43.2,  33. ,  14.7]])

### Dictionary to Dataframe

In [190]:
staff_dict = {
    "staff_name" : ["Thomson","Tsz","Eddie","Bonnie","Pauline","Kitty"],
    "dept" : ["MIS","MIS","WOM","WOM","Finance","Finance"],
    "age" : [40, 50, 60, 20, 30, 35],
    "salary" : [30000.00,20000.00,35000.00,40000.00,25000.00,10000.00]
}
staff_df = pd.DataFrame(staff_dict)
staff_df

staff_name     dept  age   salary
0    Thomson      MIS   40  30000.0
1        Tsz      MIS   50  20000.0
2      Eddie      WOM   60  35000.0
3     Bonnie      WOM   20  40000.0
4    Pauline  Finance   30  25000.0
5      Kitty  Finance   35  10000.0

### List to Dataframe

In [191]:
staff_list = (
    {"staff_name":"Thomson","dept":"MIS","age":40,"salary":30000.00},
    {"staff_name":"Tsz","dept":"MIS","age":50,"salary":20000.00},
    {"staff_name":"Eddie","dept":"WOM","age":60,"salary":35000.00},
    {"staff_name":"Bonnie","dept":"WOM","age":20,"salary":40000.00},
    {"staff_name":"Pauline","dept":"Finance","age":30,"salary":25000.00},
    {"staff_name":"Kitty","dept":"Finance","age":35,"salary":10000.00}
)
staff_df2 = pd.DataFrame.from_records(staff_list)
staff_df2

staff_name     dept  age   salary
0    Thomson      MIS   40  30000.0
1        Tsz      MIS   50  20000.0
2      Eddie      WOM   60  35000.0
3     Bonnie      WOM   20  40000.0
4    Pauline  Finance   30  25000.0
5      Kitty  Finance   35  10000.0

In [192]:
staff_dict = {
    "staff_name" : ["Thomson","Tsz","Eddie","Bonnie","Pauline","Kitty"],
    "dept" : ["MIS","MIS","WOM","WOM","Finance","Finance"],
    "age" : [40, 50, 60, 20, 30, 35],
    "salary" : [30000.00,20000.00,35000.00,40000.00,25000.00,10000.00]
}
staff_df = pd.DataFrame(staff_dict, index=['1001','1002','1003','1004','1005','1006'])
staff_df

staff_name     dept  age   salary
1001    Thomson      MIS   40  30000.0
1002        Tsz      MIS   50  20000.0
1003      Eddie      WOM   60  35000.0
1004     Bonnie      WOM   20  40000.0
1005    Pauline  Finance   30  25000.0
1006      Kitty  Finance   35  10000.0

In [193]:
staff_list = [
    {"staff_name":"Thomson","dept":"MIS","age":40,"salary":30000.00},
    {"staff_name":"Tsz","dept":"MIS","age":50,"salary":20000.00},
    {"staff_name":"Eddie","dept":"WOM","age":60,"salary":35000.00},
    {"staff_name":"Bonnie","dept":"WOM","age":20,"salary":40000.00},
    {"staff_name":"Pauline","dept":"Finance","age":30,"salary":25000.00},
    {"staff_name":"Kitty","dept":"Finance","age":35,"salary":10000.00}
]
staff_df2 = pd.DataFrame.from_records(staff_list, index=['1001','1002','1003','1004','1005','1006'])
staff_df2

staff_name     dept  age   salary
1001    Thomson      MIS   40  30000.0
1002        Tsz      MIS   50  20000.0
1003      Eddie      WOM   60  35000.0
1004     Bonnie      WOM   20  40000.0
1005    Pauline  Finance   30  25000.0
1006      Kitty  Finance   35  10000.0

In [194]:
staff_df2[staff_df2["age"]>= 40]

staff_name dept  age   salary
1001    Thomson  MIS   40  30000.0
1002        Tsz  MIS   50  20000.0
1003      Eddie  WOM   60  35000.0

In [195]:
staff_df2[(staff_df2["age"]>= 40) & (staff_df2["salary"]> 20000)]

staff_name dept  age   salary
1001    Thomson  MIS   40  30000.0
1003      Eddie  WOM   60  35000.0

In [196]:
# rearrange column order
staff_df2=staff_df2[["staff_name","dept","salary","age"]]
staff_df2

staff_name     dept   salary  age
1001    Thomson      MIS  30000.0   40
1002        Tsz      MIS  20000.0   50
1003      Eddie      WOM  35000.0   60
1004     Bonnie      WOM  40000.0   20
1005    Pauline  Finance  25000.0   30
1006      Kitty  Finance  10000.0   35

In [197]:
staff_df2["Age_Group"]=["Y" if i<40 else "M" for i in staff_df2.age ]
staff_df2

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\193485113.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  staff_df2["Age_Group"]=["Y" if i<40 else "M" for i in staff_df2.age ]


staff_name     dept   salary  age Age_Group
1001    Thomson      MIS  30000.0   40         M
1002        Tsz      MIS  20000.0   50         M
1003      Eddie      WOM  35000.0   60         M
1004     Bonnie      WOM  40000.0   20         Y
1005    Pauline  Finance  25000.0   30         Y
1006      Kitty  Finance  10000.0   35         Y

In [198]:
staff_df2["Age_Group"]=staff_df2["age"]
staff_df2

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\3180786873.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  staff_df2["Age_Group"]=staff_df2["age"]


staff_name     dept   salary  age  Age_Group
1001    Thomson      MIS  30000.0   40         40
1002        Tsz      MIS  20000.0   50         50
1003      Eddie      WOM  35000.0   60         60
1004     Bonnie      WOM  40000.0   20         20
1005    Pauline  Finance  25000.0   30         30
1006      Kitty  Finance  10000.0   35         35

In [199]:
type(staff_df2.loc[:,"age"])

pandas.core.series.Series

In [200]:
staff_df2["Age_Group"]=np.where(staff_df2["age"]>=40,"M","Y")
staff_df2

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\4097476831.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  staff_df2["Age_Group"]=np.where(staff_df2["age"]>=40,"M","Y")


staff_name     dept   salary  age Age_Group
1001    Thomson      MIS  30000.0   40         M
1002        Tsz      MIS  20000.0   50         M
1003      Eddie      WOM  35000.0   60         M
1004     Bonnie      WOM  40000.0   20         Y
1005    Pauline  Finance  25000.0   30         Y
1006      Kitty  Finance  10000.0   35         Y

In [201]:
sr=staff_df2["age"]

In [202]:
staff_df2.loc[:,"age"]="Y"
staff_df2

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\3217085644.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  staff_df2.loc[:,"age"]="Y"


staff_name     dept   salary age Age_Group
1001    Thomson      MIS  30000.0   Y         M
1002        Tsz      MIS  20000.0   Y         M
1003      Eddie      WOM  35000.0   Y         M
1004     Bonnie      WOM  40000.0   Y         Y
1005    Pauline  Finance  25000.0   Y         Y
1006      Kitty  Finance  10000.0   Y         Y

In [203]:
staff_df2["Age_Group"]="Y"

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\1473796021.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  staff_df2["Age_Group"]="Y"


In [204]:
staff_df2

staff_name     dept   salary age Age_Group
1001    Thomson      MIS  30000.0   Y         Y
1002        Tsz      MIS  20000.0   Y         Y
1003      Eddie      WOM  35000.0   Y         Y
1004     Bonnie      WOM  40000.0   Y         Y
1005    Pauline  Finance  25000.0   Y         Y
1006      Kitty  Finance  10000.0   Y         Y

In [205]:
staff_list = [
    {"staff_name":"Thomson","dept":"MIS","age":40,"salary":30000.00},
    {"staff_name":"Tsz","dept":"MIS","age":50,"salary":20000.00},
    {"staff_name":"Eddie","dept":"WOM","age":60,"salary":35000.00},
    {"staff_name":"Bonnie","dept":"WOM","age":20,"salary":40000.00},
    {"staff_name":"Pauline","dept":"Finance","age":30,"salary":25000.00},
    {"staff_name":"Kitty","dept":"Finance","age":35,"salary":10000.00}
]
staff_df3 = pd.DataFrame.from_records(staff_list)
staff_df3

staff_name     dept  age   salary
0    Thomson      MIS   40  30000.0
1        Tsz      MIS   50  20000.0
2      Eddie      WOM   60  35000.0
3     Bonnie      WOM   20  40000.0
4    Pauline  Finance   30  25000.0
5      Kitty  Finance   35  10000.0

In [206]:
staff_df3["age_group"]="Y"

In [207]:
staff_df3["age_group"]=np.where(staff_df3["age"]>=40,"M","Y")
staff_df3

staff_name     dept  age   salary age_group
0    Thomson      MIS   40  30000.0         M
1        Tsz      MIS   50  20000.0         M
2      Eddie      WOM   60  35000.0         M
3     Bonnie      WOM   20  40000.0         Y
4    Pauline  Finance   30  25000.0         Y
5      Kitty  Finance   35  10000.0         Y

In [208]:
staff_df3["age_group"]=["Y" if i<40 else "M" for i in staff_df3.age ]
staff_df3

staff_name     dept  age   salary age_group
0    Thomson      MIS   40  30000.0         M
1        Tsz      MIS   50  20000.0         M
2      Eddie      WOM   60  35000.0         M
3     Bonnie      WOM   20  40000.0         Y
4    Pauline  Finance   30  25000.0         Y
5      Kitty  Finance   35  10000.0         Y

In [209]:
df_dept=pd.DataFrame({"dept":["MIS","WOM","Finance"],
                      "dept_name":["Managemet Information System","Work Order Management","Finance and Admin"],
                      "dept_head":["Peter Lau","Tomy Yip","Jennifer Chan"]})

In [210]:
df_dept

dept                     dept_name      dept_head
0      MIS  Managemet Information System      Peter Lau
1      WOM         Work Order Management       Tomy Yip
2  Finance             Finance and Admin  Jennifer Chan

In [211]:
# join two tables
staff_df4=pd.merge(left=staff_df3,right=df_dept,how="inner",left_on="dept",right_on="dept")
#staff_df4=pd.merge(left=staff_df3,right=df_dept,how="left",left_on="dept",right_on="dept")
staff_df4

staff_name     dept  age   salary age_group                     dept_name  \
0    Thomson      MIS   40  30000.0         M  Managemet Information System   
1        Tsz      MIS   50  20000.0         M  Managemet Information System   
2      Eddie      WOM   60  35000.0         M         Work Order Management   
3     Bonnie      WOM   20  40000.0         Y         Work Order Management   
4    Pauline  Finance   30  25000.0         Y             Finance and Admin   
5      Kitty  Finance   35  10000.0         Y             Finance and Admin   

       dept_head  
0      Peter Lau  
1      Peter Lau  
2       Tomy Yip  
3       Tomy Yip  
4  Jennifer Chan  
5  Jennifer Chan

In [212]:
staff_df4

staff_name     dept  age   salary age_group                     dept_name  \
0    Thomson      MIS   40  30000.0         M  Managemet Information System   
1        Tsz      MIS   50  20000.0         M  Managemet Information System   
2      Eddie      WOM   60  35000.0         M         Work Order Management   
3     Bonnie      WOM   20  40000.0         Y         Work Order Management   
4    Pauline  Finance   30  25000.0         Y             Finance and Admin   
5      Kitty  Finance   35  10000.0         Y             Finance and Admin   

       dept_head  
0      Peter Lau  
1      Peter Lau  
2       Tomy Yip  
3       Tomy Yip  
4  Jennifer Chan  
5  Jennifer Chan

In [213]:
staff_df5=staff_df4
staff_df5

staff_name     dept  age   salary age_group                     dept_name  \
0    Thomson      MIS   40  30000.0         M  Managemet Information System   
1        Tsz      MIS   50  20000.0         M  Managemet Information System   
2      Eddie      WOM   60  35000.0         M         Work Order Management   
3     Bonnie      WOM   20  40000.0         Y         Work Order Management   
4    Pauline  Finance   30  25000.0         Y             Finance and Admin   
5      Kitty  Finance   35  10000.0         Y             Finance and Admin   

       dept_head  
0      Peter Lau  
1      Peter Lau  
2       Tomy Yip  
3       Tomy Yip  
4  Jennifer Chan  
5  Jennifer Chan

In [214]:
# Union all
staff_df6=pd.concat([staff_df4,staff_df5],axis=0)
staff_df6

staff_name     dept  age   salary age_group                     dept_name  \
0    Thomson      MIS   40  30000.0         M  Managemet Information System   
1        Tsz      MIS   50  20000.0         M  Managemet Information System   
2      Eddie      WOM   60  35000.0         M         Work Order Management   
3     Bonnie      WOM   20  40000.0         Y         Work Order Management   
4    Pauline  Finance   30  25000.0         Y             Finance and Admin   
5      Kitty  Finance   35  10000.0         Y             Finance and Admin   
0    Thomson      MIS   40  30000.0         M  Managemet Information System   
1        Tsz      MIS   50  20000.0         M  Managemet Information System   
2      Eddie      WOM   60  35000.0         M         Work Order Management   
3     Bonnie      WOM   20  40000.0         Y         Work Order Management   
4    Pauline  Finance   30  25000.0         Y             Finance and Admin   
5      Kitty  Finance   35  10000.0         Y             Finance and Admin   

       dept_head  
0      Peter Lau  
1      Peter Lau  
2       Tomy Yip  
3       Tomy Yip  
4  Jennifer Chan  
5  Jennifer Chan  
0      Peter Lau  
1      Peter Lau  
2       Tomy Yip  
3       Tomy Yip  
4  Jennifer Chan  
5  Jennifer Chan

In [215]:
staff_df6=pd.concat([staff_df4,staff_df5],axis=0)
staff_df6.reset_index() # reset index from 0.. and backup old index to a new index column

index staff_name     dept  age   salary age_group  \
0       0    Thomson      MIS   40  30000.0         M   
1       1        Tsz      MIS   50  20000.0         M   
2       2      Eddie      WOM   60  35000.0         M   
3       3     Bonnie      WOM   20  40000.0         Y   
4       4    Pauline  Finance   30  25000.0         Y   
5       5      Kitty  Finance   35  10000.0         Y   
6       0    Thomson      MIS   40  30000.0         M   
7       1        Tsz      MIS   50  20000.0         M   
8       2      Eddie      WOM   60  35000.0         M   
9       3     Bonnie      WOM   20  40000.0         Y   
10      4    Pauline  Finance   30  25000.0         Y   
11      5      Kitty  Finance   35  10000.0         Y   

                       dept_name      dept_head  
0   Managemet Information System      Peter Lau  
1   Managemet Information System      Peter Lau  
2          Work Order Management       Tomy Yip  
3          Work Order Management       Tomy Yip  
4              Finance and Admin  Jennifer Chan  
5              Finance and Admin  Jennifer Chan  
6   Managemet Information System      Peter Lau  
7   Managemet Information System      Peter Lau  
8          Work Order Management       Tomy Yip  
9          Work Order Management       Tomy Yip  
10             Finance and Admin  Jennifer Chan  
11             Finance and Admin  Jennifer Chan

In [216]:
staff_df6=pd.concat([staff_df4,staff_df5],axis=0)
staff_df6.reset_index(drop=True) # reset index from 0.. only

staff_name     dept  age   salary age_group                     dept_name  \
0     Thomson      MIS   40  30000.0         M  Managemet Information System   
1         Tsz      MIS   50  20000.0         M  Managemet Information System   
2       Eddie      WOM   60  35000.0         M         Work Order Management   
3      Bonnie      WOM   20  40000.0         Y         Work Order Management   
4     Pauline  Finance   30  25000.0         Y             Finance and Admin   
5       Kitty  Finance   35  10000.0         Y             Finance and Admin   
6     Thomson      MIS   40  30000.0         M  Managemet Information System   
7         Tsz      MIS   50  20000.0         M  Managemet Information System   
8       Eddie      WOM   60  35000.0         M         Work Order Management   
9      Bonnie      WOM   20  40000.0         Y         Work Order Management   
10    Pauline  Finance   30  25000.0         Y             Finance and Admin   
11      Kitty  Finance   35  10000.0         Y             Finance and Admin   

        dept_head  
0       Peter Lau  
1       Peter Lau  
2        Tomy Yip  
3        Tomy Yip  
4   Jennifer Chan  
5   Jennifer Chan  
6       Peter Lau  
7       Peter Lau  
8        Tomy Yip  
9        Tomy Yip  
10  Jennifer Chan  
11  Jennifer Chan

In [217]:
staff_df6

staff_name     dept  age   salary age_group                     dept_name  \
0    Thomson      MIS   40  30000.0         M  Managemet Information System   
1        Tsz      MIS   50  20000.0         M  Managemet Information System   
2      Eddie      WOM   60  35000.0         M         Work Order Management   
3     Bonnie      WOM   20  40000.0         Y         Work Order Management   
4    Pauline  Finance   30  25000.0         Y             Finance and Admin   
5      Kitty  Finance   35  10000.0         Y             Finance and Admin   
0    Thomson      MIS   40  30000.0         M  Managemet Information System   
1        Tsz      MIS   50  20000.0         M  Managemet Information System   
2      Eddie      WOM   60  35000.0         M         Work Order Management   
3     Bonnie      WOM   20  40000.0         Y         Work Order Management   
4    Pauline  Finance   30  25000.0         Y             Finance and Admin   
5      Kitty  Finance   35  10000.0         Y             Finance and Admin   

       dept_head  
0      Peter Lau  
1      Peter Lau  
2       Tomy Yip  
3       Tomy Yip  
4  Jennifer Chan  
5  Jennifer Chan  
0      Peter Lau  
1      Peter Lau  
2       Tomy Yip  
3       Tomy Yip  
4  Jennifer Chan  
5  Jennifer Chan

In [218]:
staff_df7=pd.DataFrame({"staff_name":["Sam","Florence","Kin"],
                        "dept":["WOM","Finance","MIS"],
                        "office_loc":["Kowloon","HK Island","NT"]})
staff_df7

staff_name     dept office_loc
0        Sam      WOM    Kowloon
1   Florence  Finance  HK Island
2        Kin      MIS         NT

In [219]:
# union all with different columns
staff_df8=pd.concat([staff_df6,staff_df7],axis=0).reset_index(drop=True)
staff_df8

staff_name     dept   age   salary age_group                     dept_name  \
0     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
2       Eddie      WOM  60.0  35000.0         M         Work Order Management   
3      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
4     Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
5       Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
6     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
8       Eddie      WOM  60.0  35000.0         M         Work Order Management   
9      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
10    Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
11      Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
12        Sam      WOM   NaN      NaN       NaN                           NaN   
13   Florence  Finance   NaN      NaN       NaN                           NaN   
14        Kin      MIS   NaN      NaN       NaN                           NaN   

        dept_head office_loc  
0       Peter Lau        NaN  
1       Peter Lau        NaN  
2        Tomy Yip        NaN  
3        Tomy Yip        NaN  
4   Jennifer Chan        NaN  
5   Jennifer Chan        NaN  
6       Peter Lau        NaN  
7       Peter Lau        NaN  
8        Tomy Yip        NaN  
9        Tomy Yip        NaN  
10  Jennifer Chan        NaN  
11  Jennifer Chan        NaN  
12            NaN    Kowloon  
13            NaN  HK Island  
14            NaN         NT

In [220]:
staff_df9=staff_df8[["staff_name","dept","age","salary"]]
staff_df10=staff_df8[["age_group","dept_name","dept_head","office_loc"]]
print(staff_df9)
print(staff_df10)

   staff_name     dept   age   salary
0     Thomson      MIS  40.0  30000.0
1         Tsz      MIS  50.0  20000.0
2       Eddie      WOM  60.0  35000.0
3      Bonnie      WOM  20.0  40000.0
4     Pauline  Finance  30.0  25000.0
5       Kitty  Finance  35.0  10000.0
6     Thomson      MIS  40.0  30000.0
7         Tsz      MIS  50.0  20000.0
8       Eddie      WOM  60.0  35000.0
9      Bonnie      WOM  20.0  40000.0
10    Pauline  Finance  30.0  25000.0
11      Kitty  Finance  35.0  10000.0
12        Sam      WOM   NaN      NaN
13   Florence  Finance   NaN      NaN
14        Kin      MIS   NaN      NaN
   age_group                     dept_name      dept_head office_loc
0          M  Managemet Information System      Peter Lau        NaN
1          M  Managemet Information System      Peter Lau        NaN
2          M         Work Order Management       Tomy Yip        NaN
3          Y         Work Order Management       Tomy Yip        NaN
4          Y             Finance and Admin  Jen

In [221]:
staff_df11=pd.concat([staff_df9,staff_df10],axis=1)
staff_df11

staff_name     dept   age   salary age_group                     dept_name  \
0     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
2       Eddie      WOM  60.0  35000.0         M         Work Order Management   
3      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
4     Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
5       Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
6     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
8       Eddie      WOM  60.0  35000.0         M         Work Order Management   
9      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
10    Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
11      Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
12        Sam      WOM   NaN      NaN       NaN                           NaN   
13   Florence  Finance   NaN      NaN       NaN                           NaN   
14        Kin      MIS   NaN      NaN       NaN                           NaN   

        dept_head office_loc  
0       Peter Lau        NaN  
1       Peter Lau        NaN  
2        Tomy Yip        NaN  
3        Tomy Yip        NaN  
4   Jennifer Chan        NaN  
5   Jennifer Chan        NaN  
6       Peter Lau        NaN  
7       Peter Lau        NaN  
8        Tomy Yip        NaN  
9        Tomy Yip        NaN  
10  Jennifer Chan        NaN  
11  Jennifer Chan        NaN  
12            NaN    Kowloon  
13            NaN  HK Island  
14            NaN         NT

In [222]:
# horizontal concate
staff_df11=pd.concat([staff_df9,staff_df10],axis=1).reset_index(drop=True)
staff_df11

staff_name     dept   age   salary age_group                     dept_name  \
0     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
2       Eddie      WOM  60.0  35000.0         M         Work Order Management   
3      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
4     Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
5       Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
6     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
8       Eddie      WOM  60.0  35000.0         M         Work Order Management   
9      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
10    Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
11      Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
12        Sam      WOM   NaN      NaN       NaN                           NaN   
13   Florence  Finance   NaN      NaN       NaN                           NaN   
14        Kin      MIS   NaN      NaN       NaN                           NaN   

        dept_head office_loc  
0       Peter Lau        NaN  
1       Peter Lau        NaN  
2        Tomy Yip        NaN  
3        Tomy Yip        NaN  
4   Jennifer Chan        NaN  
5   Jennifer Chan        NaN  
6       Peter Lau        NaN  
7       Peter Lau        NaN  
8        Tomy Yip        NaN  
9        Tomy Yip        NaN  
10  Jennifer Chan        NaN  
11  Jennifer Chan        NaN  
12            NaN    Kowloon  
13            NaN  HK Island  
14            NaN         NT

In [223]:
#staff_df12=staff_df8[["staff_name","dept","age","salary"]].copy()
#staff_df13=staff_df8[["age_group","dept_name","dept_head","office_loc"]].copy()
staff_df12=staff_df8[["staff_name","dept","age","salary"]]
staff_df13=staff_df8[["age_group","dept_name","dept_head","office_loc"]]
staff_df13=staff_df13.drop([10,14])
print(staff_df12)
print(staff_df13)

   staff_name     dept   age   salary
0     Thomson      MIS  40.0  30000.0
1         Tsz      MIS  50.0  20000.0
2       Eddie      WOM  60.0  35000.0
3      Bonnie      WOM  20.0  40000.0
4     Pauline  Finance  30.0  25000.0
5       Kitty  Finance  35.0  10000.0
6     Thomson      MIS  40.0  30000.0
7         Tsz      MIS  50.0  20000.0
8       Eddie      WOM  60.0  35000.0
9      Bonnie      WOM  20.0  40000.0
10    Pauline  Finance  30.0  25000.0
11      Kitty  Finance  35.0  10000.0
12        Sam      WOM   NaN      NaN
13   Florence  Finance   NaN      NaN
14        Kin      MIS   NaN      NaN
   age_group                     dept_name      dept_head office_loc
0          M  Managemet Information System      Peter Lau        NaN
1          M  Managemet Information System      Peter Lau        NaN
2          M         Work Order Management       Tomy Yip        NaN
3          Y         Work Order Management       Tomy Yip        NaN
4          Y             Finance and Admin  Jen

In [224]:
staff_df14=pd.concat([staff_df12,staff_df13],axis=1).reset_index(drop=True)
staff_df14 # row no changed even 10 and 14 deleted

staff_name     dept   age   salary age_group                     dept_name  \
0     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
2       Eddie      WOM  60.0  35000.0         M         Work Order Management   
3      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
4     Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
5       Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
6     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
8       Eddie      WOM  60.0  35000.0         M         Work Order Management   
9      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
10    Pauline  Finance  30.0  25000.0       NaN                           NaN   
11      Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
12        Sam      WOM   NaN      NaN       NaN                           NaN   
13   Florence  Finance   NaN      NaN       NaN                           NaN   
14        Kin      MIS   NaN      NaN       NaN                           NaN   

        dept_head office_loc  
0       Peter Lau        NaN  
1       Peter Lau        NaN  
2        Tomy Yip        NaN  
3        Tomy Yip        NaN  
4   Jennifer Chan        NaN  
5   Jennifer Chan        NaN  
6       Peter Lau        NaN  
7       Peter Lau        NaN  
8        Tomy Yip        NaN  
9        Tomy Yip        NaN  
10            NaN        NaN  
11  Jennifer Chan        NaN  
12            NaN    Kowloon  
13            NaN  HK Island  
14            NaN        NaN

In [225]:
staff_df14

staff_name     dept   age   salary age_group                     dept_name  \
0     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
2       Eddie      WOM  60.0  35000.0         M         Work Order Management   
3      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
4     Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
5       Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
6     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
8       Eddie      WOM  60.0  35000.0         M         Work Order Management   
9      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
10    Pauline  Finance  30.0  25000.0       NaN                           NaN   
11      Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
12        Sam      WOM   NaN      NaN       NaN                           NaN   
13   Florence  Finance   NaN      NaN       NaN                           NaN   
14        Kin      MIS   NaN      NaN       NaN                           NaN   

        dept_head office_loc  
0       Peter Lau        NaN  
1       Peter Lau        NaN  
2        Tomy Yip        NaN  
3        Tomy Yip        NaN  
4   Jennifer Chan        NaN  
5   Jennifer Chan        NaN  
6       Peter Lau        NaN  
7       Peter Lau        NaN  
8        Tomy Yip        NaN  
9        Tomy Yip        NaN  
10            NaN        NaN  
11  Jennifer Chan        NaN  
12            NaN    Kowloon  
13            NaN  HK Island  
14            NaN        NaN

In [226]:
split_row=8  # splitting dataframe by row index
staff_df14_upper=staff_df14.iloc[:split_row]
staff_df14_upper

staff_name     dept   age   salary age_group                     dept_name  \
0    Thomson      MIS  40.0  30000.0         M  Managemet Information System   
1        Tsz      MIS  50.0  20000.0         M  Managemet Information System   
2      Eddie      WOM  60.0  35000.0         M         Work Order Management   
3     Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
4    Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
5      Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
6    Thomson      MIS  40.0  30000.0         M  Managemet Information System   
7        Tsz      MIS  50.0  20000.0         M  Managemet Information System   

       dept_head office_loc  
0      Peter Lau        NaN  
1      Peter Lau        NaN  
2       Tomy Yip        NaN  
3       Tomy Yip        NaN  
4  Jennifer Chan        NaN  
5  Jennifer Chan        NaN  
6      Peter Lau        NaN  
7      Peter Lau        NaN

In [227]:
split_row=8  # splitting dataframe by row index
staff_df14_lower=staff_df14.iloc[split_row:,:].reset_index(drop=True)
staff_df14_lower

staff_name     dept   age   salary age_group              dept_name  \
0      Eddie      WOM  60.0  35000.0         M  Work Order Management   
1     Bonnie      WOM  20.0  40000.0         Y  Work Order Management   
2    Pauline  Finance  30.0  25000.0       NaN                    NaN   
3      Kitty  Finance  35.0  10000.0         Y      Finance and Admin   
4        Sam      WOM   NaN      NaN       NaN                    NaN   
5   Florence  Finance   NaN      NaN       NaN                    NaN   
6        Kin      MIS   NaN      NaN       NaN                    NaN   

       dept_head office_loc  
0       Tomy Yip        NaN  
1       Tomy Yip        NaN  
2            NaN        NaN  
3  Jennifer Chan        NaN  
4            NaN    Kowloon  
5            NaN  HK Island  
6            NaN        NaN

In [228]:
staff_df14.groupby(["dept"]).sum()["salary"]
# df2.groupby(["Courses"]).sum()

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\134054530.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  staff_df14.groupby(["dept"]).sum()["salary"]


dept
Finance     70000.0
MIS        100000.0
WOM        150000.0
Name: salary, dtype: float64

In [229]:
staff_df14.groupby(["dept"]).sum()

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\21140169.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  staff_df14.groupby(["dept"]).sum()


age    salary
dept                    
Finance  130.0   70000.0
MIS      180.0  100000.0
WOM      160.0  150000.0

In [230]:
staff_df14_lower["dept"]

0        WOM
1        WOM
2    Finance
3    Finance
4        WOM
5    Finance
6        MIS
Name: dept, dtype: object

In [231]:
staff_df14_lower.loc[:,"dept"]  # return series with single column

0        WOM
1        WOM
2    Finance
3    Finance
4        WOM
5    Finance
6        MIS
Name: dept, dtype: object

In [232]:
# https://towardsdatascience.com/how-to-use-loc-and-iloc-for-selecting-data-in-pandas-bd09cb4c3d79
# iloc using index vs loc using label

In [233]:
staff_df14_lower.loc[:,"dept":"salary"]  # return dataframe with multiple columns

dept   age   salary
0      WOM  60.0  35000.0
1      WOM  20.0  40000.0
2  Finance  30.0  25000.0
3  Finance  35.0  10000.0
4      WOM   NaN      NaN
5  Finance   NaN      NaN
6      MIS   NaN      NaN

In [234]:
staff_df14_lower.loc[:,"dept":"dept"]  # return dataframe with single column

dept
0      WOM
1      WOM
2  Finance
3  Finance
4      WOM
5  Finance
6      MIS

In [235]:
type(staff_df14_lower.loc[:,"dept":"dept"])
# pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

In [236]:
type(staff_df14_lower.loc[:,"dept"])
# pandas.core.frame.DataFrame

pandas.core.series.Series

In [237]:
staff_df14[staff_df14["dept"]=="MIS"]

staff_name dept   age   salary age_group                     dept_name  \
0     Thomson  MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz  MIS  50.0  20000.0         M  Managemet Information System   
6     Thomson  MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz  MIS  50.0  20000.0         M  Managemet Information System   
14        Kin  MIS   NaN      NaN       NaN                           NaN   

    dept_head office_loc  
0   Peter Lau        NaN  
1   Peter Lau        NaN  
6   Peter Lau        NaN  
7   Peter Lau        NaN  
14        NaN        NaN

In [238]:
staff_df14[staff_df14["dept"]=="MIS"][["staff_name","salary","dept_head"]]
# select staff_name, salary, dept_head from staff_df14 where dept='MIS'

staff_name   salary  dept_head
0     Thomson  30000.0  Peter Lau
1         Tsz  20000.0  Peter Lau
6     Thomson  30000.0  Peter Lau
7         Tsz  20000.0  Peter Lau
14        Kin      NaN        NaN

In [239]:
grouped=staff_df14.groupby(["dept"])
grouped.get_group("MIS")

staff_name dept   age   salary age_group                     dept_name  \
0     Thomson  MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz  MIS  50.0  20000.0         M  Managemet Information System   
6     Thomson  MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz  MIS  50.0  20000.0         M  Managemet Information System   
14        Kin  MIS   NaN      NaN       NaN                           NaN   

    dept_head office_loc  
0   Peter Lau        NaN  
1   Peter Lau        NaN  
6   Peter Lau        NaN  
7   Peter Lau        NaN  
14        NaN        NaN

In [240]:
staff_df14.groupby(["dept"]).get_group("MIS")

staff_name dept   age   salary age_group                     dept_name  \
0     Thomson  MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz  MIS  50.0  20000.0         M  Managemet Information System   
6     Thomson  MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz  MIS  50.0  20000.0         M  Managemet Information System   
14        Kin  MIS   NaN      NaN       NaN                           NaN   

    dept_head office_loc  
0   Peter Lau        NaN  
1   Peter Lau        NaN  
6   Peter Lau        NaN  
7   Peter Lau        NaN  
14        NaN        NaN

In [241]:
staff_df14.groupby(["dept"]).get_group("Finance")

staff_name     dept   age   salary age_group          dept_name  \
4     Pauline  Finance  30.0  25000.0         Y  Finance and Admin   
5       Kitty  Finance  35.0  10000.0         Y  Finance and Admin   
10    Pauline  Finance  30.0  25000.0       NaN                NaN   
11      Kitty  Finance  35.0  10000.0         Y  Finance and Admin   
13   Florence  Finance   NaN      NaN       NaN                NaN   

        dept_head office_loc  
4   Jennifer Chan        NaN  
5   Jennifer Chan        NaN  
10            NaN        NaN  
11  Jennifer Chan        NaN  
13            NaN  HK Island

In [242]:
staff_df14.groupby(["dept"]).get_group("WOM")

staff_name dept   age   salary age_group              dept_name dept_head  \
2       Eddie  WOM  60.0  35000.0         M  Work Order Management  Tomy Yip   
3      Bonnie  WOM  20.0  40000.0         Y  Work Order Management  Tomy Yip   
8       Eddie  WOM  60.0  35000.0         M  Work Order Management  Tomy Yip   
9      Bonnie  WOM  20.0  40000.0         Y  Work Order Management  Tomy Yip   
12        Sam  WOM   NaN      NaN       NaN                    NaN       NaN   

   office_loc  
2         NaN  
3         NaN  
8         NaN  
9         NaN  
12    Kowloon

In [243]:
staff_df14[staff_df14["dept"]=="WOM"]
# staff_df14.groupby(["dept"]).get_group("WOM") same 

staff_name dept   age   salary age_group              dept_name dept_head  \
2       Eddie  WOM  60.0  35000.0         M  Work Order Management  Tomy Yip   
3      Bonnie  WOM  20.0  40000.0         Y  Work Order Management  Tomy Yip   
8       Eddie  WOM  60.0  35000.0         M  Work Order Management  Tomy Yip   
9      Bonnie  WOM  20.0  40000.0         Y  Work Order Management  Tomy Yip   
12        Sam  WOM   NaN      NaN       NaN                    NaN       NaN   

   office_loc  
2         NaN  
3         NaN  
8         NaN  
9         NaN  
12    Kowloon

In [244]:
for dname in staff_df14['dept'].unique():
    print(dname)
# select distinct dept from staff_df14 

MIS
WOM
Finance


In [245]:
staff_df14['dept'].unique()

array(['MIS', 'WOM', 'Finance'], dtype=object)

In [246]:
staff_dept_list=[]
for dname in staff_df14['dept'].unique():
     staff_dept_list.append(staff_df14.groupby(["dept"]).get_group(dname))
staff_dept_list[0]

staff_name dept   age   salary age_group                     dept_name  \
0     Thomson  MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz  MIS  50.0  20000.0         M  Managemet Information System   
6     Thomson  MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz  MIS  50.0  20000.0         M  Managemet Information System   
14        Kin  MIS   NaN      NaN       NaN                           NaN   

    dept_head office_loc  
0   Peter Lau        NaN  
1   Peter Lau        NaN  
6   Peter Lau        NaN  
7   Peter Lau        NaN  
14        NaN        NaN

In [247]:
staff_dept_list={}
for dname in staff_df14['dept'].unique():
     staff_dept_list[dname]=staff_df14.groupby(["dept"]).get_group(dname)
staff_dept_list["WOM"]

staff_name dept   age   salary age_group              dept_name dept_head  \
2       Eddie  WOM  60.0  35000.0         M  Work Order Management  Tomy Yip   
3      Bonnie  WOM  20.0  40000.0         Y  Work Order Management  Tomy Yip   
8       Eddie  WOM  60.0  35000.0         M  Work Order Management  Tomy Yip   
9      Bonnie  WOM  20.0  40000.0         Y  Work Order Management  Tomy Yip   
12        Sam  WOM   NaN      NaN       NaN                    NaN       NaN   

   office_loc  
2         NaN  
3         NaN  
8         NaN  
9         NaN  
12    Kowloon

In [248]:
staff_df14=pd.concat([staff_df12,staff_df13],axis=1).reset_index(drop=True)

In [249]:
# store function
staff_df15=staff_df14.copy()
def fn_ins_salary(s):
    return s * 1.1500
staff_df15['new_salary']=staff_df15['salary'].apply(fn_ins_salary)
staff_df15

staff_name     dept   age   salary age_group                     dept_name  \
0     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
2       Eddie      WOM  60.0  35000.0         M         Work Order Management   
3      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
4     Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
5       Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
6     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
8       Eddie      WOM  60.0  35000.0         M         Work Order Management   
9      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
10    Pauline  Finance  30.0  25000.0       NaN                           NaN   
11      Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
12        Sam      WOM   NaN      NaN       NaN                           NaN   
13   Florence  Finance   NaN      NaN       NaN                           NaN   
14        Kin      MIS   NaN      NaN       NaN                           NaN   

        dept_head office_loc  new_salary  
0       Peter Lau        NaN     34500.0  
1       Peter Lau        NaN     23000.0  
2        Tomy Yip        NaN     40250.0  
3        Tomy Yip        NaN     46000.0  
4   Jennifer Chan        NaN     28750.0  
5   Jennifer Chan        NaN     11500.0  
6       Peter Lau        NaN     34500.0  
7       Peter Lau        NaN     23000.0  
8        Tomy Yip        NaN     40250.0  
9        Tomy Yip        NaN     46000.0  
10            NaN        NaN     28750.0  
11  Jennifer Chan        NaN     11500.0  
12            NaN    Kowloon         NaN  
13            NaN  HK Island         NaN  
14            NaN        NaN         NaN

In [250]:
staff_df14

staff_name     dept   age   salary age_group                     dept_name  \
0     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
1         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
2       Eddie      WOM  60.0  35000.0         M         Work Order Management   
3      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
4     Pauline  Finance  30.0  25000.0         Y             Finance and Admin   
5       Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
6     Thomson      MIS  40.0  30000.0         M  Managemet Information System   
7         Tsz      MIS  50.0  20000.0         M  Managemet Information System   
8       Eddie      WOM  60.0  35000.0         M         Work Order Management   
9      Bonnie      WOM  20.0  40000.0         Y         Work Order Management   
10    Pauline  Finance  30.0  25000.0       NaN                           NaN   
11      Kitty  Finance  35.0  10000.0         Y             Finance and Admin   
12        Sam      WOM   NaN      NaN       NaN                           NaN   
13   Florence  Finance   NaN      NaN       NaN                           NaN   
14        Kin      MIS   NaN      NaN       NaN                           NaN   

        dept_head office_loc  
0       Peter Lau        NaN  
1       Peter Lau        NaN  
2        Tomy Yip        NaN  
3        Tomy Yip        NaN  
4   Jennifer Chan        NaN  
5   Jennifer Chan        NaN  
6       Peter Lau        NaN  
7       Peter Lau        NaN  
8        Tomy Yip        NaN  
9        Tomy Yip        NaN  
10            NaN        NaN  
11  Jennifer Chan        NaN  
12            NaN    Kowloon  
13            NaN  HK Island  
14            NaN        NaN

In [251]:
# store function
staff_df16=staff_df14.copy()
def fn_ins_salary(s):
    return s * 1.1500
staff_df16.insert(4, 'new_salary', staff_df16['salary'].apply(fn_ins_salary)) # add column with a specific position
staff_df16

staff_name     dept   age   salary  new_salary age_group  \
0     Thomson      MIS  40.0  30000.0     34500.0         M   
1         Tsz      MIS  50.0  20000.0     23000.0         M   
2       Eddie      WOM  60.0  35000.0     40250.0         M   
3      Bonnie      WOM  20.0  40000.0     46000.0         Y   
4     Pauline  Finance  30.0  25000.0     28750.0         Y   
5       Kitty  Finance  35.0  10000.0     11500.0         Y   
6     Thomson      MIS  40.0  30000.0     34500.0         M   
7         Tsz      MIS  50.0  20000.0     23000.0         M   
8       Eddie      WOM  60.0  35000.0     40250.0         M   
9      Bonnie      WOM  20.0  40000.0     46000.0         Y   
10    Pauline  Finance  30.0  25000.0     28750.0       NaN   
11      Kitty  Finance  35.0  10000.0     11500.0         Y   
12        Sam      WOM   NaN      NaN         NaN       NaN   
13   Florence  Finance   NaN      NaN         NaN       NaN   
14        Kin      MIS   NaN      NaN         NaN       NaN   

                       dept_name      dept_head office_loc  
0   Managemet Information System      Peter Lau        NaN  
1   Managemet Information System      Peter Lau        NaN  
2          Work Order Management       Tomy Yip        NaN  
3          Work Order Management       Tomy Yip        NaN  
4              Finance and Admin  Jennifer Chan        NaN  
5              Finance and Admin  Jennifer Chan        NaN  
6   Managemet Information System      Peter Lau        NaN  
7   Managemet Information System      Peter Lau        NaN  
8          Work Order Management       Tomy Yip        NaN  
9          Work Order Management       Tomy Yip        NaN  
10                           NaN            NaN        NaN  
11             Finance and Admin  Jennifer Chan        NaN  
12                           NaN            NaN    Kowloon  
13                           NaN            NaN  HK Island  
14                           NaN            NaN        NaN

In [252]:
# https://sparkbyexamples.com/pandas/pandas-apply-function-usage-examples/

In [253]:
# store function (using lambda expression)
staff_df17=staff_df14.copy()
staff_df17.insert(4, 'new_salary', staff_df17['salary'].apply(lambda x: x * 1.15)) # add column with a specific position
staff_df17

staff_name     dept   age   salary  new_salary age_group  \
0     Thomson      MIS  40.0  30000.0     34500.0         M   
1         Tsz      MIS  50.0  20000.0     23000.0         M   
2       Eddie      WOM  60.0  35000.0     40250.0         M   
3      Bonnie      WOM  20.0  40000.0     46000.0         Y   
4     Pauline  Finance  30.0  25000.0     28750.0         Y   
5       Kitty  Finance  35.0  10000.0     11500.0         Y   
6     Thomson      MIS  40.0  30000.0     34500.0         M   
7         Tsz      MIS  50.0  20000.0     23000.0         M   
8       Eddie      WOM  60.0  35000.0     40250.0         M   
9      Bonnie      WOM  20.0  40000.0     46000.0         Y   
10    Pauline  Finance  30.0  25000.0     28750.0       NaN   
11      Kitty  Finance  35.0  10000.0     11500.0         Y   
12        Sam      WOM   NaN      NaN         NaN       NaN   
13   Florence  Finance   NaN      NaN         NaN       NaN   
14        Kin      MIS   NaN      NaN         NaN       NaN   

                       dept_name      dept_head office_loc  
0   Managemet Information System      Peter Lau        NaN  
1   Managemet Information System      Peter Lau        NaN  
2          Work Order Management       Tomy Yip        NaN  
3          Work Order Management       Tomy Yip        NaN  
4              Finance and Admin  Jennifer Chan        NaN  
5              Finance and Admin  Jennifer Chan        NaN  
6   Managemet Information System      Peter Lau        NaN  
7   Managemet Information System      Peter Lau        NaN  
8          Work Order Management       Tomy Yip        NaN  
9          Work Order Management       Tomy Yip        NaN  
10                           NaN            NaN        NaN  
11             Finance and Admin  Jennifer Chan        NaN  
12                           NaN            NaN    Kowloon  
13                           NaN            NaN  HK Island  
14                           NaN            NaN        NaN

In [254]:
staff_df18=staff_df14.copy() 
staff_df18=staff_df18.reindex(sorted(staff_df18.columns), axis=1)  # rearrange column names by order
staff_df18

age age_group     dept      dept_head                     dept_name  \
0   40.0         M      MIS      Peter Lau  Managemet Information System   
1   50.0         M      MIS      Peter Lau  Managemet Information System   
2   60.0         M      WOM       Tomy Yip         Work Order Management   
3   20.0         Y      WOM       Tomy Yip         Work Order Management   
4   30.0         Y  Finance  Jennifer Chan             Finance and Admin   
5   35.0         Y  Finance  Jennifer Chan             Finance and Admin   
6   40.0         M      MIS      Peter Lau  Managemet Information System   
7   50.0         M      MIS      Peter Lau  Managemet Information System   
8   60.0         M      WOM       Tomy Yip         Work Order Management   
9   20.0         Y      WOM       Tomy Yip         Work Order Management   
10  30.0       NaN  Finance            NaN                           NaN   
11  35.0         Y  Finance  Jennifer Chan             Finance and Admin   
12   NaN       NaN      WOM            NaN                           NaN   
13   NaN       NaN  Finance            NaN                           NaN   
14   NaN       NaN      MIS            NaN                           NaN   

   office_loc   salary staff_name  
0         NaN  30000.0    Thomson  
1         NaN  20000.0        Tsz  
2         NaN  35000.0      Eddie  
3         NaN  40000.0     Bonnie  
4         NaN  25000.0    Pauline  
5         NaN  10000.0      Kitty  
6         NaN  30000.0    Thomson  
7         NaN  20000.0        Tsz  
8         NaN  35000.0      Eddie  
9         NaN  40000.0     Bonnie  
10        NaN  25000.0    Pauline  
11        NaN  10000.0      Kitty  
12    Kowloon      NaN        Sam  
13  HK Island      NaN   Florence  
14        NaN      NaN        Kin

In [255]:
staff_df19=staff_df14.copy() 
staff_df19=staff_df19.reindex(sorted(staff_df19.columns), axis=1)
staff_df19.head(2)

age age_group dept  dept_head                     dept_name office_loc  \
0  40.0         M  MIS  Peter Lau  Managemet Information System        NaN   
1  50.0         M  MIS  Peter Lau  Managemet Information System        NaN   

    salary staff_name  
0  30000.0    Thomson  
1  20000.0        Tsz

In [256]:
staff_df19.iloc[:,0:7].head(2)

age age_group dept  dept_head                     dept_name office_loc  \
0  40.0         M  MIS  Peter Lau  Managemet Information System        NaN   
1  50.0         M  MIS  Peter Lau  Managemet Information System        NaN   

    salary  
0  30000.0  
1  20000.0

In [257]:
staff_df20=staff_df14.copy()
staff_df20.insert(4, 'new_salary', staff_df20['salary'].apply(lambda x: x * 1.15)) # add column with a specific position
staff_df20[["new_salary","salary"]].apply(np.sum, axis=0)

new_salary    368000.0
salary        320000.0
dtype: float64

In [258]:
staff_df20

staff_name     dept   age   salary  new_salary age_group  \
0     Thomson      MIS  40.0  30000.0     34500.0         M   
1         Tsz      MIS  50.0  20000.0     23000.0         M   
2       Eddie      WOM  60.0  35000.0     40250.0         M   
3      Bonnie      WOM  20.0  40000.0     46000.0         Y   
4     Pauline  Finance  30.0  25000.0     28750.0         Y   
5       Kitty  Finance  35.0  10000.0     11500.0         Y   
6     Thomson      MIS  40.0  30000.0     34500.0         M   
7         Tsz      MIS  50.0  20000.0     23000.0         M   
8       Eddie      WOM  60.0  35000.0     40250.0         M   
9      Bonnie      WOM  20.0  40000.0     46000.0         Y   
10    Pauline  Finance  30.0  25000.0     28750.0       NaN   
11      Kitty  Finance  35.0  10000.0     11500.0         Y   
12        Sam      WOM   NaN      NaN         NaN       NaN   
13   Florence  Finance   NaN      NaN         NaN       NaN   
14        Kin      MIS   NaN      NaN         NaN       NaN   

                       dept_name      dept_head office_loc  
0   Managemet Information System      Peter Lau        NaN  
1   Managemet Information System      Peter Lau        NaN  
2          Work Order Management       Tomy Yip        NaN  
3          Work Order Management       Tomy Yip        NaN  
4              Finance and Admin  Jennifer Chan        NaN  
5              Finance and Admin  Jennifer Chan        NaN  
6   Managemet Information System      Peter Lau        NaN  
7   Managemet Information System      Peter Lau        NaN  
8          Work Order Management       Tomy Yip        NaN  
9          Work Order Management       Tomy Yip        NaN  
10                           NaN            NaN        NaN  
11             Finance and Admin  Jennifer Chan        NaN  
12                           NaN            NaN    Kowloon  
13                           NaN            NaN  HK Island  
14                           NaN            NaN        NaN

In [259]:
staff_df20[["new_salary"]].apply(np.sum, axis=0)

new_salary    368000.0
dtype: float64

In [260]:
staff_df20[["salary"]].apply(np.sum, axis=0)

salary    320000.0
dtype: float64

In [261]:
# select dept, sum(salary), sum(new_salary) from staff_df20 group by dept
#warnings.filterwarnings('ignore')
staff_df20.groupby("dept").sum()[["salary","new_salary"]]

C:\Users\Thomson Yeung\AppData\Local\Temp\ipykernel_11148\1050789006.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  staff_df20.groupby("dept").sum()[["salary","new_salary"]]


salary  new_salary
dept                         
Finance   70000.0     80500.0
MIS      100000.0    115000.0
WOM      150000.0    172500.0

In [262]:
staff_df20.groupby("dept")[["salary","new_salary"]].sum()

salary  new_salary
dept                         
Finance   70000.0     80500.0
MIS      100000.0    115000.0
WOM      150000.0    172500.0

In [263]:
# select dept, sum(salary), sum(new_salary) from staff_df20 group by dept order by dept desc
staff_df20.groupby("dept")[["salary","new_salary"]].sum().sort_values(['dept'], ascending=False)

salary  new_salary
dept                         
WOM      150000.0    172500.0
MIS      100000.0    115000.0
Finance   70000.0     80500.0

In [264]:
# select dept, sum(salary), sum(new_salary) from staff_df20 group by dept order by dept
staff_df20.groupby("dept")[["salary","new_salary"]].sum().sort_values(['dept'])

salary  new_salary
dept                         
Finance   70000.0     80500.0
MIS      100000.0    115000.0
WOM      150000.0    172500.0